version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:9.6.10
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - postgres
    restart: unless-stopped
  
#  pgadmin:
#    container_name: pgadmin_container
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#       - pgadmin:/root/.pgadmin
#
#    ports:
#      - "${PGADMIN_PORT}:80"
#    networks:
#      - postgres
#    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
